package nowpaymentlibs

type CreateInvoiceStatus string

const (
	CREATE_INVOICE_STATUS_WAIT_PAY CreateInvoiceStatus = "CREATE_INVOICE_STATUS_WAIT_PAY"
	CREATE_INVOICE_STATUS_PAY      CreateInvoiceStatus = "CREATE_INVOICE_STATUS_PAY"
	CREATE_INVOICE_STATUS_CANCELL  CreateInvoiceStatus = "CREATE_INVOICE_STATUS_CANCELL"
	CREATE_INVOICE_STATUS_FINISH   CreateInvoiceStatus = "CREATE_INVOICE_STATUS_FINISH"
)
